name: Deploy to GCP VM

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3

      # Step 2: Authenticate with GCP
      - name: Authenticate with GCP
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" > keyfile.json
          gcloud auth activate-service-account --key-file=keyfile.json
          gcloud config set project ${{ secrets.GOOGLE_PROJECT }}
          gcloud compute config-ssh

      # Step 3: SSH into GCP VM and deploy the Docker container
      - name: Deploy Docker Container on GCP VM
        run: |
          gcloud compute ssh hng00 \
            --zone=us-central1-c \
            --command="docker stop fastapi-container || true && \
                       docker rm fastapi-container || true && \
                       docker pull red4u/fastapi-book-project:latest && \
                       docker run -d --name fastapi-container -p 8000:8000 red4u/fastapi-book-project:latest"
